name: Check
env: 
  WOLFRAM_SYSTEM_ID: Linux-x86-64
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
on: 
  push: 
    branches:  [main]
  pull_request: 
    branches:  [main]
  workflow_dispatch:
jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
      RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
    timeout-minutes: 360
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v3
    - name: Check
      id: check-paclet-step
      uses: WolframResearch/check-paclet@v1.9.0
      with: 
        target: Submit
        paclet_cicd_version: 0.32.0
        definition_notebook: ./ResourceDefenition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0